name: "Lock closed issues and PRs"

on:


  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:
    secrets:
      AWS_PEPITO_DEMENTIAPP_ACCOUNT_ARN:
        required: true
  # Debug: Allow triggering job manually in github-actions WebUI
  workflow_dispatch: {}


jobs:
  connecto_to_aws:
    - name: "☁️👷 Configure AWS credentials with OIDC role"
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_PEPITO_DEMENTIAPP_ACCOUNT_ARN }}
        aws-region: eu-west-1
        role-session-name: DeployRole

    - name: "List s3"
      run: |
        aws s3 list-buckets